import React, { useRef, useEffect } from 'react';

import katex from 'katex';

import { cleanAlternativeContent } from '../../utils/utils';

interface HtmlMathRendererProps {
  html: string;
  className?: string;
  alternativeLabel?: string;
}

/**
 * HtmlMathRenderer — A reusable, self-contained component that:
 * 1. Injects HTML content into the DOM.
 * 2. Finds all `<span data-type="math-inline">` elements (generated by the Tiptap MathNode).
 * 3. Renders their `data-latex` attribute using KaTeX so formulas display correctly.
 * 4. Optionally cleans alternative prefixes (A), B), etc.) if alternativeLabel is provided.
 *
 * Usage: <HtmlMathRenderer html={item.enunciado} className="prose" />
 * Drop it in anywhere you need to display rich content with math.
 */
const HtmlMathRenderer: React.FC<HtmlMathRendererProps> = ({
  html,
  className,
  alternativeLabel,
}) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = containerRef.current;
    if (!el || !html) {
      if (el) el.innerHTML = '';
      return;
    }

    // 1. Inject the HTML (cleaned if requested)
    let processedHtml = html;
    if (alternativeLabel) {
      processedHtml = cleanAlternativeContent(html, alternativeLabel);
    }

    // 1.5 Replace asterisks with bullet points (dots) globally as requested
    processedHtml = processedHtml.replace(/\*/g, '•');

    // 1.6 Intensify gray backgrounds globally as requested
    processedHtml = processedHtml.replace(/bg-gray-100/g, 'bg-gray-200 border border-gray-200')
                                .replace(/bg-gray-300/g, 'bg-gray-200 border border-gray-200');

    el.innerHTML = processedHtml;

    // 2. Find all math-inline spans and render with KaTeX
    const mathSpans = el.querySelectorAll<HTMLSpanElement>(
      'span[data-type="math-inline"]'
    );
    mathSpans.forEach((span) => {
      const latex = span.getAttribute('data-latex');
      if (latex) {
        try {
          katex.render(latex, span, {
            throwOnError: false,
            displayMode: false,
            output: 'html',
          });
        } catch {
          span.innerHTML = `<span class="math-error" title="Error LaTeX">⚠ ${latex}</span>`;
        }
      }
    });
  }, [html, alternativeLabel]);

  return <div ref={containerRef} className={className} />;
};

export default HtmlMathRenderer;
